# Site settings
title: Wojciech Ptak
description: "Human, Learner, Developer"
url: 'http://wojciech-ptak.eu'
baseurl: '/'
google_analytics: 'UA-43268157-3'
disqus_shortname: 'wojciechp'

author:
  name: 'Wojciech Ptak'
  email: wojtek.ptak@gmail.com
#  twitter_username: joshgerdes
#  facebook_username: joshgerdes
  github_username: wojciechp
#  linkedin_username:  joshgerdes

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'

collections:
  - skills

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['CNAME', 'README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
